### ISSUE TITLE
Issue with Shift + e

### ISSUE THREAD

**Issue by theFahmid** [suryaya/Arabic-Phonetic-Keyboard-Linux#2]
According to [Omar Al Zabir's Arabic Phonetic Keyboard Layout](https://arabic.omaralzabir.com/), pressing the `Shift + e` should print a `Small Alif` or `ٰ`, known as `খাড়া যবর` in Bengali. But, in this layout, it prints a `damma` or `pesh` or ` ُ` instead of the Small Alif.

To know more about the Small Alif: https://unicode-table.com/en/0670/

**Comment by hydroEng** [comment]
Thanks for letting me know. I'll fix this shortly.

**Comment by hydroEng** [comment]
I've fixed the issue; can you please download the layout again and check if it works?

**Comment by theFahmid** [comment]
@suryaya Yeah! It's working fine now... جَزَاكَ اللّٰهُ خَيْرًا
