### ISSUE TITLE
Arabic Numerals don't appear

### ISSUE THREAD

**Issue by theFahmid** [suryaya/Arabic-Phonetic-Keyboard-Linux#3]
Assalamu Alaikum. As the Issue Title states, Arabic Numerals don't appear if I press the buttons of the number pad.

**Comment by hydroEng** [comment]
Wa alaykum as-salam, I haven't coded the arabic numbers to work with the numpad, though I can do that once I get some spare time. Right now you can access them via level 3 key + top row numbers (I wanted to keep using english numerals personally so I didn't replace the first level.

To set up level 3 key go to Gnome tweaks > keyboard and mouse > Additional Layout options > choose a 3rd level key
